name: Squash Commits on Main

on:
  push:
    branches:
      - main # Trigger on push to main branch
  workflow_dispatch: # Allow manual triggering

jobs:
  squash-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper squashing

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"

      - name: Squash commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the current branch (should be main)
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [ "$CURRENT_BRANCH" != "main" ]; then
            echo "Error: Not on main branch. Current branch is $CURRENT_BRANCH."
            exit 1
          fi

          # Get the commit message of the latest commit
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)

          # Count the number of commits on main
          COMMIT_COUNT=$(git rev-list --count HEAD)

          if [ "$COMMIT_COUNT" -le 1 ]; then
            echo "Only one or no commits exist. No squashing needed."
            exit 0
          fi

          # Reset to the first commit and squash all commits
          git reset --soft $(git rev-list --max-parents=0 HEAD)
          git commit -m "$COMMIT_MESSAGE"

          # Force push the squashed commit to main
          git push --force-with-lease